export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const SERACH_TODO = 'SERACH_TODO'; 

export const VISIBILITY_FILTER = {
	SHOW_ALL: 'SHOW_ALL',
	SHOW_ACTIVE: 'SHOW_ACTIVE',
	SHOW_COMPLETE: 'SHOW_COMPLETE'
}